name = "wiggles-api"
main = "src/index.ts"
compatibility_date = "2022-09-11"
account_id = "e5933c765c57d2f3a58d86973c88362c"

[vars]
GOOGLE_CLIENT_ID = "153513713709-ci5ajsramjotbt7apiuvambqan36n6m2.apps.googleusercontent.com"
ENV = "development"

[[kv_namespaces]]
  binding = "WIGGLES"
  id = "a6c8694133f14020808088b6c53300a8"
  preview_id = "a6c8694133f14020808088b6c53300a8"
