name = "wiggles-api"
main = "src/index.ts"
compatibility_date = "2022-09-11"
account_id = "e5933c765c57d2f3a58d86973c88362c"

route = { pattern = "wiggle-room.xyz/api/*", zone_name = "wiggle-room.xyz" }

[vars]
AUTH0_DOMAIN = "dev-zeu8o0dkwj1gdp7c.eu.auth0.com"
AUTH0_AUDIENCE = "https://wiggle-room.xyz"
ENV = "production"

[[kv_namespaces]]
  binding = "WIGGLES"
  id = "a6c8694133f14020808088b6c53300a8"
  preview_id = "a6c8694133f14020808088b6c53300a8"
