name = "wiggles-api"
main = "src/index.ts"
compatibility_date = "2022-09-11"
account_id = "e5933c765c57d2f3a58d86973c88362c"

[assets]
directory = "../web/dist"
binding = "ASSETS"

[vars]
AUDIENCE = "d20630ce701d4cae70898078ceb3ff409ed25e4230224bd461e1b91537438e05"
DOMAIN = "https://johnpangalos.cloudflareaccess.com"
ENV = "development"

[[kv_namespaces]]
  binding = "WIGGLES"
  id = "a884d6ec4f0740f1acb1fcab72096746"
  preview_id = "96652f6d962a4712a239304868414da2"


