name: Preview
on:
  pull_request:
    paths:
      - "app/**"
      - "workers/**"
      - "public/**"
      - "package.json"
      - "wrangler.jsonc"
      - "vite.config.ts"
      - "react-router.config.ts"
      - ".github/workflows/preview-web.yml"

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write

    name: Cloudflare Pages Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-deps

      - name: Build
        run: pnpm build

      - name: Deploy Preview
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: e5933c765c57d2f3a58d86973c88362c
          projectName: wiggles
          directory: build/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
